Fix two flakey tests
These two tests are failing for me locally on master:

    ________________________________________________ TestEncodeJWT.test_it_uses_one_hour_lifetime_by_default ________________________________________________

    self = <tests.unit.lms.validation.authentication._helpers._jwt_test.TestEncodeJWT object at 0x7f4deea63c50>

        def test_it_uses_one_hour_lifetime_by_default(self):
            jwt_str = _jwt.encode_jwt({}, "test_secret")
            decoded_payload = jwt.decode(jwt_str, "test_secret", algorithms=["HS256"])
            lifetime_minutes = self._jwt_lifetime(decoded_payload) / 60

    >       assert round(lifetime_minutes) == 60
    E       assert 120 == 60
    E        +  where 120 = round(119.98486773173015)

    tests/unit/lms/validation/authentication/_helpers/_jwt_test.py:95: AssertionError
    ______________________________________________________ TestEncodeJWT.test_it_uses_custom_lifetime _______________________________________________________

    self = <tests.unit.lms.validation.authentication._helpers._jwt_test.TestEncodeJWT object at 0x7f4deec06eb8>

        def test_it_uses_custom_lifetime(self):
            jwt_str = _jwt.encode_jwt(
                {}, "test_secret", lifetime=datetime.timedelta(hours=24)
            )
            decoded_payload = jwt.decode(jwt_str, "test_secret", algorithms=["HS256"])
            lifetime_hours = self._jwt_lifetime(decoded_payload) / (60 * 60)

    >       assert round(lifetime_hours) == 24
    E       assert 25 == 24
    E        +  where 25 = round(24.99973412030273)

    tests/unit/lms/validation/authentication/_helpers/_jwt_test.py:104: AssertionError

I think it's probably best to mock `datetime` for these time-based
tests. I've also mocked `jwt` because if you don't it looks like `jwt`
makes its own calls to `datetime` so you still get time-related
failures. The two tests in question don't really need to be tested
against the real `jwt` anyway: they're just tests for what expiry time
our code passes in the payload to `jwt.encode()`. Mocking `jwt` is
easier than decoding the payload and then trying to calculate the
expected expiry timestamp.