Remove hard-coded authorities from LMS
`models/region.py` contains a hard-coded expectation that the
`H_AUTHORITY` envvar will be either `"lms.hypothes.is"` or
`"lms.ca.hypothes.is"`.

You can test this on `main` by setting the envvar
`H_AUTHORITY=lms.staging.hypothes.is` and then running `make dev`.
You'll see that app startup crashes with:

    ValueError: Cannot find a region for the authority 'lms.staging.hypothes.is'

This is making it impossible to deploy our new staging environment.

The code in `region.py` further contains the implicit expectation that
there will be a one:one mapping between authorities and region codes,
such that the `"lms.hypothes.is"` and `"lms.staging.hypothes.is"`
authorities cannot both use the region code `"us"`. So it's not
possible to simply add "lms.staging.hypothes.is" to the list of
acceptable authorities unless we're willing to give it a region code
other than "us".

This commit attempts to rectify the situation by removing both the
hard-coded list of possible authorities and the one:one assumption, with
unknown consequences for https://github.com/hypothesis/report/.