Fix factories.User.application_instance
This has never worked: sub-factories must be other factories, not model
objects:

```python
$ make shell
...

Environment:
  ...
  f            The test factories for quickly creating objects.
  factories    The test factories for quickly creating objects.
  ...

>>> user = factories.User()
---------------------------------------------------------------------------
AssociatedClassError                      Traceback (most recent call last)
...
AssociatedClassError: <BuildStep for <StepBuilder(<SQLAlchemyOptions for UserFactory>, strategy='create')>>: Attempting to recursing into a non-factory object <class 'lms.models.application_instance.ApplicationInstance'>
```

The reason why the tests were still passing is that they never call
`factories.User()` without passing in an `application_instance`
argument.

This commit fixes it so that `factories.User()` with no
`application_instance` uses `factories.ApplicationInstance` as a
sub-factory to generate a new `ApplicationInstance` for the user.