Fix user unique constraint
`user_id` (the LTI user ID) should be unique (within an application instance).

And, separetely from that, `h_userid` (the user ID of the corresponding
h user) should also be unique (again, within an application instance).

But those are two separate unique constraints not one. The current
constraint allows two users to have the same LTI ID as long as they have
different h IDs and vice-versa:

```sql
INSERT INTO public.user (application_instance_id, user_id, h_userid) VALUES (1, 'user_id_1', 'h_userid_1');

-- Insert a second user with the same user_id as the first.
INSERT INTO public.user (application_instance_id, user_id, h_userid) VALUES (1, 'user_id_1', 'h_userid_2');

--Insert a second user with the same h_userid as the first.
INSERT INTO public.user (application_instance_id, user_id, h_userid) VALUES (1, 'user_id_2', 'h_userid_1');

SELECT application_instance_id, user_id, h_userid FROM public.user;
 application_instance_id |  user_id  |  h_userid
-------------------------+-----------+------------
                       1 | user_id_1 | h_userid_1
                       1 | user_id_1 | h_userid_2
                       1 | user_id_2 | h_userid_1
(3 rows)
```

This PR splits it into two separate constraints so that we can't have
two users with the same LTI ID or two users with the same h ID within
the same application instance:

```sql
INSERT INTO public.user (application_instance_id, user_id, h_userid) VALUES (1, 'user_id_1', 'h_userid_1');

-- Inserting a second user with the same user_id as the first fails.
INSERT INTO public.user (application_instance_id, user_id, h_userid) VALUES (1, 'user_id_1', 'h_userid_2');
ERROR:  duplicate key value violates unique constraint "uq__user__user_id"
DETAIL:  Key (user_id, application_instance_id)=(user_id_1, 1) already exists.

--Inserting a second user with the same h_userid as the first fails.
INSERT INTO public.user (application_instance_id, user_id, h_userid) VALUES (1, 'user_id_2', 'h_userid_1');
ERROR:  duplicate key value violates unique constraint "uq__user__h_userid"
DETAIL:  Key (h_userid, application_instance_id)=(h_userid_1, 1) already exists.
```