Fix /canvas_oauth_callback crash
If you load `http://localhost:8001/canvas_oauth_callback` in a browser
tab it crashes with:

    AttributeError: 'NoneType' object has no attribute 'oauth_consumer_key'

`request.lti_user` is `None` so when
`CanvasAPIAuthorizeViews.__init__()` tries to do `self.canvas_api_client
= request.find_service(name="canvas_api_client")` it crashes because
`CanvasAPIClient` tries to access `request.lti_user.oauth_consumer_key`.

The actual view (`CanvasAPIAuthorizeViews.oauth2_redirect()`) won't be
called because it's protected by `permission="canvas_api"` and all
requests that have the `"canvas_api"` permission have a
`request.lti_user`.

But Pyramid still calls the view class's `__init__()` method.

So move the `CanvasAPIClient` initialization into the view itself, so
that it'll only be called for valid requests.